---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mystack
  namespace: argocd
spec:
  description: mystack
  sourceRepos:
    - '*'
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc